#!/bin/bash
current_shell_file_path=$(cd "$(dirname "$0")"; pwd)

cd ${current_shell_file_path}
pwd  && ls -a

branch_name=$(git status | grep 'On branch' | awk '{print $3}')

if [[ -z $branch_name ]];
then
    if [[ -z $1 ]];
    then
        branch_name=$1
    else
        echo "请输入镜像标签,如v1.0.0"
        exit 1
    fi
fi

#sonarqube:lts-alpine-zh
docker build -t ascs/sonarqube:$branch_name  .  --no-cache=true
